### ISSUE TITLE
Model Richardsona

### ISSUE THREAD

**Issue by michalkonieczny91** [pelzu12345/cyclistshop#2]
W tym miejscu
https://github.com/pelzu12345/cyclistshop/blob/37b54d6952a5cc3ac85a9a406f8696a834cf0021/src/main/java/com/example/cyclistshop/hello/CustomerControler.java#L21

nie ma potrzeby dodawania "add" kiedy masz metodę Post
sama metoda post jest dopełnieniem co robi metoda

**Comment by pelzu12345** [comment]
zrobione
