### ISSUE TITLE
HttpResponse

### ISSUE THREAD

**Issue by michalkonieczny91** [pelzu12345/cyclistshop#4]
Tak całkiem szczerze to tu jakiś kod http powineneś przynajmniej zwracać
https://github.com/pelzu12345/cyclistshop/blob/37b54d6952a5cc3ac85a9a406f8696a834cf0021/src/main/java/com/example/cyclistshop/hello/CustomerControler.java#L22

**Comment by pelzu12345** [comment]
jakbyś mógł rozwinąć :)
