### ISSUE TITLE
Wielkość liter

### ISSUE THREAD

**Issue by michalkonieczny91** [pelzu12345/cyclistshop#5]
Takie SQL-owe rzeczy raczej pisze się UPPER_CASE 
https://github.com/pelzu12345/cyclistshop/blob/37b54d6952a5cc3ac85a9a406f8696a834cf0021/src/main/java/com/example/cyclistshop/domain/Customer.java#L9

**Comment by pelzu12345** [comment]
Usunąłem linijkę niech zostanie domyślna nazwa CUSTOMER
