### ISSUE TITLE
Gettery Settery

### ISSUE THREAD

**Issue by michalkonieczny91** [pelzu12345/cyclistshop#7]
Potrzebne Ci te wszystkie gettery i settery czy dałeś po prostu na pałę?
https://github.com/pelzu12345/cyclistshop/blob/37b54d6952a5cc3ac85a9a406f8696a834cf0021/src/main/java/com/example/cyclistshop/domain/Customer.java#L10

**Comment by pelzu12345** [comment]
Jak nie będzie setterów to nulle powstawiają mi sie do bazy danych :P:P
a gettery sie może przydadzą na później :) np. raz getId się przydał.
