### ISSUE TITLE
Formatowianie

### ISSUE THREAD

**Issue by michalkonieczny91** [pelzu12345/cyclistshop#8]
Średnik nie dolega do zmiennej generalnie w całym projekcie staraj się dbać o takie pierdoły
https://github.com/pelzu12345/cyclistshop/blob/37b54d6952a5cc3ac85a9a406f8696a834cf0021/src/main/java/com/example/cyclistshop/hello/CustomerControler.java#L13
np możesz skorzystać z autoformatu w intelij alt+ctrl+l

**Comment by pelzu12345** [comment]
ok
